customize-config:
  host_service_name: "micro-task-service"
  host_service_addr: "192.168.1.134:10000"
  etcd:
    address: 47.236.140.65
    port: 2379
#    address: 192.168.1.182
#    port: 2379

system:
  use-db: true
  db-type: mysql

mysql:
  path: 192.168.1.182
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: sms
  username: root
  password: 90!@#RCSdev
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
  debug: true

redis:
  db: 1
  addr: 192.168.18.244:6379
  password:

zap:
  level: info
  prefix: '[go-micro-play] '
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: false
  log-in-console: true

