apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: registry.cn-hangzhou.aliyuncs.com/wxg-uat/micro-task-service:v0.1801
          workingDir: "/opt/service/"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-file
              mountPath: /opt/service/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-file
          configMap:
            name: micro-task-config