# kubectl create configmap micro-gateway-config -n demo --from-file=config.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  label:
    app: micro-gateway
  name: micro-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-gateway
  template:
    metadata:
      labels:
        app: micro-gateway
    spec:
      containers:
        - name: micro-gateway
          image: registry.cn-hangzhou.aliyuncs.com/wxg-uat/micro-gateway-service:010801
          workingDir: "/opt/service/"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-file
              mountPath: /opt/service/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-file
          configMap:
            name: micro-gateway-config