apiVersion: v1
kind: Service
metadata:
  namespace: demo
  labels:
    app: gateway-service
  name: gateway-service
spec:
  selector:
    app: micro-gateway
  type: LoadBalancer
  ports:
    - port: 12000
      protocol: TCP
      targetPort: 8080